table ip nat {
    chain PREROUTING {
        type nat hook prerouting priority dstnat; policy accept;
        # tinkerspace-vm SSH (users)
        iifname "eth0" tcp dport 2222 dnat to 10.10.0.2:2222
    }

    chain POSTROUTING {
        type nat hook postrouting priority srcnat; policy accept;
        # masquerade outbound traffic on WireGuard
        oifname "wg0" masquerade
    }
}

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        iifname "lo" accept
        ct state established,related accept
        tcp dport 22 accept
        tcp dport 80 accept
        tcp dport 443 accept
        udp dport 51820 accept
        tcp dport 2222 accept
    }

    chain forward {
        type filter hook forward priority 0; policy accept;
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}
