table ip nat {
    chain PREROUTING {
        type nat hook prerouting priority dstnat; policy accept;
        iifname "eth0" tcp dport 2222 dnat to 10.10.0.2:2222
    }

    chain POSTROUTING {
        type nat hook postrouting priority srcnat; policy accept;
        oifname "wg0" masquerade
    }
}
table ip filter {
    chain INPUT {
        type filter hook input priority filter; policy drop;
        ct state established,related accept
        iifname "lo" accept
        tcp dport 22 accept
        tcp dport { 80, 443 } accept
        tcp dport 2222 accept
        udp dport 51820 accept
    }

    chain FORWARD {
        type filter hook forward priority filter; policy drop;
        ct state established,related accept
        iifname "eth0" oifname "wg0" accept
        iifname "wg0" oifname "eth0" accept
    }
}
