[sssd]
services = nss, pam
domains = authentik

[domain/authentik]
id_provider = ldap
auth_provider = ldap
ldap_uri = ldap://10.70.123.10:389
ldap_search_base = dc=ldap,dc=goauthentik,dc=io
ldap_user_search_base = ou=users,dc=ldap,dc=goauthentik,dc=io
ldap_group_search_base = ou=groups,dc=ldap,dc=goauthentik,dc=io
ldap_default_bind_dn = cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io
ldap_default_authtok = CHANGE_ME
ldap_tls_reqcert = never
ldap_user_object_class = user
ldap_group_object_class = group
ldap_user_name = cn
ldap_user_uid_number = uidNumber
ldap_user_gid_number = gidNumber
ldap_user_home_directory = homeDirectory
ldap_schema = rfc2307bis
enumerate = true
cache_credentials = true
default_shell = /bin/bash
fallback_homedir = /home/%u
